import {Roboto} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from '@clerk/themes'

const roboto = Roboto({subsets:['latin'] , weight:['100','300','400','500','700','900']})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider  appearance={{
      baseTheme: shadesOfPurple,
    }}>
    <html lang="en">
      <body
        className={`${roboto.className} antialiased bg-background text-col`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
